function B = get_B_matrix(r,d,m_ball,m_body,I_ball,I_body_xy,I_body_z,g)
%get_B_matrix
%    B = get_B_matrix(R,D,M_BALL,M_BODY,I_ball,I_body_xy,I_body_z,G)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    12-Dec-2025 16:51:25

t2 = d.^2;
t3 = r.^2;
t4 = I_ball.*I_body_xy;
t5 = d.*m_body.*r;
t6 = m_body.*t2;
t7 = m_ball.*t3;
t8 = m_body.*t3;
t9 = I_ball.*t6;
t10 = I_body_xy.*t7;
t11 = I_body_xy.*t8;
t12 = t6.*t7;
t13 = I_body_xy+t5+t6;
t14 = I_ball+t5+t7+t8;
t15 = t4+t9+t10+t11+t12;
t16 = 1.0./t15;
t17 = r.*t13.*t16;
t18 = t14.*t16;
B = reshape([0.0,0.0,0.0,0.0,0.0,t17,0.0,t18,0.0,0.0,0.0,0.0,-t17,0.0,t18,0.0],[8,2]);
end
