function A = get_A_matrix(r,d,m_ball,m_body,I_ball,I_body_xy,I_body_z,g)
%get_A_matrix
%    A = get_A_matrix(R,D,M_BALL,M_BODY,I_ball,I_body_xy,I_body_z,G)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    12-Dec-2025 16:51:25

t2 = d.^2;
t3 = m_body.^2;
t4 = r.^2;
t5 = I_ball.*I_body_xy;
t6 = m_ball.*t4;
t7 = m_body.*t4;
t8 = I_ball.*m_body.*t2;
t9 = I_body_xy.*t6;
t10 = I_body_xy.*t7;
t11 = m_body.*t2.*t6;
t12 = I_ball+t6+t7;
t13 = t5+t8+t9+t10+t11;
t14 = 1.0./t13;
t15 = g.*t2.*t3.*t4.*t14;
t16 = d.*g.*m_body.*t12.*t14;
A = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t15,0.0,t16,0.0,0.0,0.0,0.0,0.0,0.0,t15,0.0,t16,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0],[8,8]);
end
