function dv_eq = getDriverAcceleration(u_wheel,r,m_w,m_s)
%getDriverAcceleration
%    DV_EQ = getDriverAcceleration(U_WHEEL,R,M_W,M_S)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    11-Dec-2025 14:22:38

dv_eq = u_wheel./(r.*(m_s+m_w));
end
