function f = getFVector(x,y,theta,phi,Omega,alpha,dotx,doty,dottheta,dotphi,omega,dotalpha,r,d,m_w,m_s,I_wpitch,I_wyawroll,g)
%getFVector
%    F = getFVector(X,Y,THETA,PHI,Omega,ALPHA,DOTX,DOTY,DOTTHETA,DOTPHI,OMEGA,DOTALPHA,R,D,M_W,M_S,I_wpitch,I_wyawroll,G)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    11-Dec-2025 10:06:46

t2 = cos(alpha);
t3 = cos(phi);
t4 = sin(alpha);
t5 = cos(theta);
t6 = sin(phi);
t7 = sin(theta);
t8 = alpha.*2.0;
t9 = d.^2;
t10 = dotphi.^2;
t11 = dotalpha.^2;
t12 = dottheta.^2;
t13 = phi.*2.0;
t14 = r.^2;
t15 = t2.^2;
t16 = t3.^2;
t17 = sin(t8);
t18 = sin(t13);
mt1 = [-d.*m_s.*t4.*t5.*t11-d.*m_s.*t4.*t5.*t12-m_s.*r.*t6.*t7.*t10-m_s.*r.*t6.*t7.*t12-m_w.*r.*t6.*t7.*t10-m_w.*r.*t6.*t7.*t12-d.*m_s.*t2.*t6.*t7.*t10-d.*m_s.*t2.*t6.*t7.*t11-d.*m_s.*t2.*t6.*t7.*t12-d.*dotalpha.*dottheta.*m_s.*t2.*t7.*2.0+dotphi.*dottheta.*m_s.*r.*t3.*t5.*2.0+dotphi.*dottheta.*m_w.*r.*t3.*t5.*2.0-d.*dotphi.*dotalpha.*m_s.*t3.*t4.*t7.*2.0+d.*dotphi.*dottheta.*m_s.*t2.*t3.*t5.*2.0-d.*dotalpha.*dottheta.*m_s.*t4.*t5.*t6.*2.0];
mt2 = [-d.*m_s.*t4.*t7.*t11-d.*m_s.*t4.*t7.*t12+m_s.*r.*t5.*t6.*t10+m_s.*r.*t5.*t6.*t12+m_w.*r.*t5.*t6.*t10+m_w.*r.*t5.*t6.*t12+d.*m_s.*t2.*t5.*t6.*t10+d.*m_s.*t2.*t5.*t6.*t11+d.*m_s.*t2.*t5.*t6.*t12+d.*dotalpha.*dottheta.*m_s.*t2.*t5.*2.0+dotphi.*dottheta.*m_s.*r.*t3.*t7.*2.0+dotphi.*dottheta.*m_w.*r.*t3.*t7.*2.0+d.*dotphi.*dotalpha.*m_s.*t3.*t4.*t5.*2.0+d.*dotphi.*dottheta.*m_s.*t2.*t3.*t7.*2.0-d.*dotalpha.*dottheta.*m_s.*t4.*t6.*t7.*2.0];
mt3 = [I_wpitch.*dotphi.*dottheta.*t18-I_wyawroll.*dotphi.*dottheta.*t18+I_wpitch.*dotphi.*omega.*t3+dotphi.*dotalpha.*m_s.*t3.*t9.*2.0+dotphi.*dottheta.*m_s.*t14.*t18+dotphi.*dottheta.*m_w.*t14.*t18+m_s.*t2.*t4.*t6.*t9.*t10-d.*dotalpha.*dottheta.*m_s.*r.*t4.*2.0-dotphi.*dotalpha.*m_s.*t3.*t9.*t15.*2.0+d.*m_s.*r.*t4.*t6.*t10-d.*m_s.*r.*t4.*t6.*t11+d.*dotalpha.*dottheta.*m_s.*r.*t4.*t16.*2.0+dotphi.*dottheta.*m_s.*t3.*t6.*t9.*t15.*2.0+dotalpha.*dottheta.*m_s.*t2.*t4.*t9.*t16.*2.0+d.*dotphi.*dottheta.*m_s.*r.*t2.*t3.*t6.*4.0];
mt4 = [I_wpitch.*t12.*t18.*(-1.0./2.0)+(I_wyawroll.*t12.*t18)./2.0-g.*m_s.*r.*t6-g.*m_w.*r.*t6-(m_s.*t12.*t14.*t18)./2.0-(m_w.*t12.*t14.*t18)./2.0-I_wpitch.*dottheta.*omega.*t3-dotphi.*dotalpha.*m_s.*t9.*t17-d.*g.*m_s.*t2.*t6-m_s.*t3.*t6.*t9.*t12.*t15-d.*dotphi.*dotalpha.*m_s.*r.*t4.*2.0-dotalpha.*dottheta.*m_s.*t3.*t9.*t15.*2.0-d.*dotalpha.*dottheta.*m_s.*r.*t2.*t3.*2.0-d.*m_s.*r.*t2.*t3.*t6.*t12.*2.0;I_wpitch.*dotphi.*dottheta.*t3;d.*m_s.*((d.*t10.*t17)./2.0-g.*t3.*t4+r.*t4.*t10+r.*t4.*t12-r.*t4.*t12.*t16+d.*dotphi.*dottheta.*t3.*t15.*2.0+dotphi.*dottheta.*r.*t2.*t3.*2.0-d.*t2.*t4.*t12.*t16)];
f = [mt1;mt2;mt3;mt4];
end
