function f_vec = getFVector(in1,in2,v,dv,r,d,m_w,m_s,I_wpitch,I_wyawroll,g)
%getFVector
%    F_VEC = getFVector(IN1,IN2,V,DV,R,D,M_W,M_S,I_wpitch,I_wyawroll,G)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    11-Dec-2025 14:22:38

alpha = in1(3,:);
dotphi = in2(2,:);
dotalpha = in2(3,:);
dottheta = in2(1,:);
phi = in1(2,:);
t2 = cos(alpha);
t3 = cos(phi);
t4 = sin(alpha);
t5 = sin(phi);
t6 = d.^2;
t7 = dotphi.^2;
t8 = dottheta.^2;
t9 = phi.*2.0;
t13 = 1.0./r;
t10 = t2.^2;
t11 = t3.^2;
t12 = sin(t9);
mt1 = [t13.*(I_wpitch.*dv.*t5+I_wpitch.*dotphi.*t3.*v+I_wpitch.*dotphi.*dottheta.*r.*t12-I_wyawroll.*dotphi.*dottheta.*r.*t12+d.*dv.*m_s.*r.*t2.*t5+dotphi.*dotalpha.*m_s.*r.*t3.*t6.*2.0-dotphi.*dotalpha.*m_s.*r.*t3.*t6.*t10.*2.0+d.*dotphi.*m_s.*r.*t2.*t3.*v-d.*dotalpha.*m_s.*r.*t4.*t5.*v+m_s.*r.*t2.*t4.*t5.*t6.*t7+dotphi.*dottheta.*m_s.*r.*t3.*t5.*t6.*t10.*2.0+dotalpha.*dottheta.*m_s.*r.*t2.*t4.*t6.*t11.*2.0);-t13.*((I_wpitch.*r.*t8.*t12)./2.0-(I_wyawroll.*r.*t8.*t12)./2.0+I_wpitch.*dottheta.*t3.*v+dotphi.*dotalpha.*m_s.*r.*t6.*sin(alpha.*2.0)+d.*g.*m_s.*r.*t2.*t5+dotalpha.*dottheta.*m_s.*r.*t3.*t6.*t10.*2.0+d.*dottheta.*m_s.*r.*t2.*t3.*v+m_s.*r.*t3.*t5.*t6.*t8.*t10)];
mt2 = [d.*m_s.*(dv.*t2-g.*t3.*t4+d.*t2.*t4.*t7+dottheta.*t4.*t5.*v+d.*dotphi.*dottheta.*t3.*t10.*2.0-d.*t2.*t4.*t8.*t11)];
f_vec = [mt1;mt2];
end
