function B = getInputMatrix(x,y,theta,phi,Omega,alpha,dotx,doty,dottheta,dotphi,omega,dotalpha,r,d,m_w,m_s,I_wpitch,I_wyawroll,g)
%getInputMatrix
%    B = getInputMatrix(X,Y,THETA,PHI,Omega,ALPHA,DOTX,DOTY,DOTTHETA,DOTPHI,OMEGA,DOTALPHA,R,D,M_W,M_S,I_wpitch,I_wyawroll,G)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    11-Dec-2025 10:06:46

B = reshape([0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[6,3]);
end
