function B_mat = getInputMatrix
%getInputMatrix
%    B_mat = getInputMatrix

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    11-Dec-2025 14:22:38

B_mat = reshape([0.0,0.0,-1.0,0.0,1.0,0.0],[3,2]);
end
