function M = getMassMatrix(x,y,theta,phi,Omega,alpha,dotx,doty,dottheta,dotphi,omega,dotalpha,r,d,m_w,m_s,I_wpitch,I_wyawroll,g)
%getMassMatrix
%    M = getMassMatrix(X,Y,THETA,PHI,Omega,ALPHA,DOTX,DOTY,DOTTHETA,DOTPHI,OMEGA,DOTALPHA,R,D,M_W,M_S,I_wpitch,I_wyawroll,G)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    11-Dec-2025 10:06:46

t2 = cos(alpha);
t3 = cos(phi);
t4 = sin(alpha);
t5 = cos(theta);
t6 = sin(phi);
t7 = sin(theta);
t8 = m_s+m_w;
t9 = d.^2;
t10 = r.^2;
t11 = t2.^2;
t12 = t3.^2;
t13 = I_wpitch.*t6;
t14 = m_s.*t9;
t15 = m_s.*t10;
t16 = m_w.*t10;
t17 = m_s.*r.*t6.*t7;
t18 = m_w.*r.*t6.*t7;
t19 = d.*m_s.*r.*t2.*2.0;
t20 = d.*m_s.*t4.*t5;
t21 = m_s.*r.*t3.*t5;
t22 = m_w.*r.*t3.*t5;
t23 = d.*m_s.*t4.*t7;
t24 = m_s.*r.*t3.*t7;
t25 = m_s.*r.*t5.*t6;
t26 = m_w.*r.*t3.*t7;
t27 = m_w.*r.*t5.*t6;
t28 = d.*m_s.*r.*t3.*t4;
t29 = d.*m_s.*t2.*t3.*t5;
t30 = d.*m_s.*t2.*t3.*t7;
t31 = d.*m_s.*t2.*t5.*t6;
t32 = d.*m_s.*t2.*t6.*t7;
t33 = -t21;
t34 = -t22;
t35 = -t23;
t36 = -t28;
t37 = -t29;
t38 = t2.*t3.*t4.*t14;
t40 = t24+t26+t30;
t43 = t17+t18+t20+t32;
t39 = -t38;
t42 = t33+t34+t37;
t44 = t25+t27+t31+t35;
t41 = t36+t39;
M = reshape([t8,0.0,t44,t40,0.0,d.*m_s.*(t2.*t5-t4.*t6.*t7),0.0,t8,t43,t42,0.0,d.*m_s.*(t2.*t7+t4.*t5.*t6),t44,t43,I_wpitch+t14+t15+t16+t19-I_wpitch.*t12+I_wyawroll.*t12-t12.*t15-t12.*t16-t11.*t12.*t14-d.*m_s.*r.*t2.*t12.*2.0,t41,t13,d.*m_s.*(d.*t6+r.*t2.*t6),t40,t42,t41,I_wyawroll+t15+t16+t19+t11.*t14,0.0,0.0,0.0,0.0,t13,0.0,I_wpitch,0.0,t6.*t35+d.*m_s.*t2.*t5,t6.*t20+d.*m_s.*t2.*t7,t6.*t14+d.*m_s.*r.*t2.*t6,0.0,0.0,t14],[6,6]);
end
