function M = getMassMatrix(in1,in2,v,r,d,m_w,m_s,I_wpitch,I_wyawroll,g)
%getMassMatrix
%    M = getMassMatrix(IN1,IN2,V,R,D,M_W,M_S,I_wpitch,I_wyawroll,G)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    11-Dec-2025 14:22:38

alpha = in1(3,:);
phi = in1(2,:);
t2 = cos(alpha);
t3 = cos(phi);
t4 = sin(alpha);
t5 = sin(phi);
t6 = d.^2;
t9 = 1.0./r;
t7 = t2.^2;
t8 = t3.^2;
t10 = m_s.*t5.*t6;
t11 = m_s.*t2.*t3.*t4.*t6;
t12 = -t11;
M = reshape([t9.*(I_wpitch.*r-I_wpitch.*r.*t8+I_wyawroll.*r.*t8+m_s.*r.*t6-m_s.*r.*t6.*t7.*t8),t12,t10,t12,t9.*(I_wyawroll.*r+m_s.*r.*t6.*t7),0.0,t10,0.0,m_s.*t6],[3,3]);
end
